version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  kubernetes: circleci/kubernetes@1.3.0
  helm: circleci/helm@1.2.0
  snyk: snyk/snyk@1.1.2

_snyk_options: &snyk_options
  project: "${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}"
  organization: "legal-aid-agency"
  severity-threshold: "critical"
  fail-on-issues: true
  monitor-on-build: false
  token-variable: SNYK_TOKEN
  additional-arguments: --policy-path=.snyk

# ------------------
# EXECUTORS
# ------------------
executors:
  cloud-platform-executor:
    resource_class: small
    docker:
      - image: ministryofjustice/cloud-platform-tools

# ------------------
# COMMANDS
# ------------------
commands:
  deploy-to:
    description: >
      Deploy image to the specified environment
    parameters:
      environment:
        description: Destination environment
        type: string
      token:
        description: CircleCI Service account token
        type: string
    steps:
      - checkout
      - run:
          name: Authenticate with cluster
          command: |
            echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./ca.crt
            kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./ca.crt --server=https://${K8S_CLUSTER_NAME}
            kubectl config set-credentials circleci --token=<< parameters.token >>
            kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci --namespace=cfe-crime-<< parameters.environment >>
            kubectl config use-context ${K8S_CLUSTER_NAME}
            kubectl --namespace=cfe-crime-<< parameters.environment >> get pods
      - helm/upgrade-helm-chart:
          namespace: cfe-crime-<< parameters.environment >>
          update-repositories: false
          chart: ./deploy/helm/
          release-name: cfe-crime
          values: ./deploy/helm/values/<< parameters.environment >>.yaml
          values-to-override: image.tag=${CIRCLE_SHA1},image.repository=$AWS_ECR_ACCOUNT_URL/laa-eligibility-platform/cfe-crime-ecr

# ------------------
# JOBS
# ------------------
jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      K8S_CLUSTER_NAME: "DF366E49809688A3B16EEC29707D8C09.gr7.eu-west-2.eks.amazonaws.com"
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Install Dependencies
          command: ./gradlew build -x test
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - persist_to_workspace:
          root: .
          paths:
            - build

  scan_app:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - attach_workspace:
          at: .
      - snyk/scan:
          <<: *snyk_options

  test_and_assemble:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Run build test
          command: ./gradlew clean build
      - store_test_results:
          # view test in CircleCI
          path: build/test-results
      #test (execution , jacoco, etc) saved
      - store_artifacts:
          path: build/reports/jacoco/test
          destination: test_result
      - store_artifacts:
          path: build/reports/jacoco
          destination: test_coverage
      - run:
          name: Assemble JAR
          command: ./gradlew assemble
      - store_artifacts:
          path: build/libs

  build_and_scan_image:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-ecr/build-image:
          repo: laa-eligibility-platform/cfe-crime-ecr
          tag: "${CIRCLE_SHA1}"
      - snyk/scan:
          docker-image-name: "$AWS_ECR_ACCOUNT_URL/laa-eligibility-platform/cfe-crime-ecr:${CIRCLE_SHA1}"
          <<: *snyk_options

  build_and_push_image:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          repo: laa-eligibility-platform/cfe-crime-ecr
          tag: "${CIRCLE_SHA1}"
          attach-workspace: true
          workspace-root: .
          path: .
          extra-build-args: |
            --build-arg COMMIT_ID=${CIRCLE_SHA1} \
            --build-arg BUILD_TAG=${CIRCLE_SHA1} \
            --build-arg APP_BRANCH=${CIRCLE_BRANCH} \
            --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) \

  deploy-dev:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: dev
          token: ${CIRCLE_CI_TOKEN_DEV}

# ------------------
# WORKFLOWS
# ------------------
workflows:
  version: 2

  build-deploy-master:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

      - scan_app:
          requires:
            - build

      - test_and_assemble:
          requires:
            - build

      - build_and_scan_image:
          requires:
            - scan_app
            - test_and_assemble

      - build_and_push_image:
          requires:
            - build_and_scan_image

      - deploy-dev:
          requires:
            - build_and_push_image

  build-deploy-branch:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main

      - scan_app:
          requires:
            - build

      - test_and_assemble:
          requires:
            - build

      - build_and_scan_image:
          requires:
            - test_and_assemble

      - build_and_push_image:
          requires:
            - scan_app
            - build_and_scan_image

      - deploy-dev:
          requires:
            - build_and_push_image

