# Default values for cfe-crime dev
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 10m
    memory: 125Mi

ingress:
  className: modsec
  hosts:
    - cfe-crime-dev.cloud-platform.service.justice.gov.uk
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "cfe-crime-cfe-crime-dev-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On

deploy:
  host: cfe-crime-dev.cloud-platform.service.justice.gov.uk

postgresql:
  enabled: false

threshold:
  useTestData: 'true'

legalFrameworkApi:
  host: https://legal-framework-api.cloud-platform.service.justice.gov.uk

sentry:
  enabled: enabled

notifications:
  errorMessageTemplateId: e6d49396-455c-4aca-aab0-16f8411e76f5
  recipient: patrick.gleeson@digital.justice.gov.uk,michael.blatherwick@digital.justice.gov.uk,stephen.p.dicks@digital.justice.gov.uk,william.clarke@digital.justice.gov.uk
