# Default values for cfe-crime dev
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

resources:
  limits:
    cpu: 900m
    memory: 1G
  requests:
    cpu: 500m
    memory: 150Mi

ingress:
  className: modsec
  hosts:
    - cfe-crime-dev.cloud-platform.service.justice.gov.uk
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "cfe-crime-cfe-crime-dev-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On

deploy:
  host: cfe-crime-dev.cloud-platform.service.justice.gov.uk

sentry:
  enabled: enabled
