apiVersion: v1
kind: Service
metadata:
  name: {{ include "cfe-crime.fullname" . }}
  labels:
    {{- include "cfe-crime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if not (eq (toString .Values.actuator.port) "http") }}
    - port: {{ .Values.actuator.port }}
      targetPort: actuator
      protocol: TCP
      name: actuator
    {{- end }}      
  selector:
    {{- include "cfe-crime.selectorLabels" . | nindent 4 }}
